### ISSUE TITLE
Feature request: tga2raw and possibly building back of dsres

### ISSUE THREAD

**Issue by masterjg** [glampert/reverse-engineering-dungeon-siege#4]
I know this is probably out of scope of this project, but would you be willing to create cmd utils to do tga2raw conversion? And also probably building back of dsres? I think there are no cmd tools to do that currently for DS1...

**Comment by masterjg** [comment]
UPDATE: Found RTC.exe tool to build back dsres. However couldn't find any cmd util to convert tga back to raw. Would you be willing to develop this? Or maybe you know any alternatives that I could you via command line?

**Comment by glampert** [comment]
Yes, it could be easily done. I can add a new cmd line util for that.

**Comment by glampert** [comment]
`tga2raw` command line utility added to the prebuilt binaries zip in https://github.com/glampert/reverse-engineering-dungeon-siege/blob/master/build/Release_Win10_x64.zip

It works in the same way as the other image converters (raw2tga and raw2png). Note that one limitation of this conversion tool is that the resulting `.raw` will have a single mipmap since TGAs do not support the concept of mipmaps, which might not be ideal if you want to get modded textures back into the game. Maybe in the future we might want to support combining a bunch of TGAs or PNGs that each represent a precomputed mipmap of a texture and package them together into a `.raw`.
