### ISSUE TITLE
tankdump cant open LOA dsres

### ISSUE THREAD

**Issue by masterjg** [glampert/reverse-engineering-dungeon-siege#5]
LOA dsres is unopenable...

`tankdump.exe Expansion.dsres -H`
```
-------- TANK HEADER --------
Product id.........: DSig
Tank id............: Tank
Header version.....: 1.0.2
DirSet offset......: 0x16432BD0 (356.2 Megabytes)
FileSet offset.....: 0x1643C288 (356.23 Megabytes)
Index size.........: 742.89 Kilobytes
Data offset........: 0x00000324 (804 Bytes)
Product version....: 5.0.0  10.0.3  1.0.16
Minimum version....: 5.0.0  3.7.210  1.0.8
ERROR.: Invalid TankFile::Priority flag!
```

Same happens with ExpVoices.dsres...

**Comment by masterjg** [comment]
Also on some other dsres I got this:
```
ERROR.: Invalid file parent offset: 104
```

**Comment by glampert** [comment]
OK, I'm not sure I've ever tested this on a LOA tank file, but it's likely because of version differences.

I don't have access to any sample LOA tank file I could test on at the moment. @masterjg, would you be able to upload an example file somewhere that gives this error?

Cheers!

**Comment by jsmars** [comment]
I've notices this as well, hopefully it's not too late to provide a DSLOA file for you to test and get it fixed.
I've noticed that it works fine on the ExpVoices.dsres file, but not on the Expansion.dsres, and it crashes on the following line, likely due to it being the first PSD file contained therein.

`Extracting resource file "/art/bitmaps/terrain/forest_sequoia/wall/b_t_for02_wal_gate_alpha.psd"`

I've also included a file from DS2, despite DS1 being far superior imo, do you think it would be possible to add support for extracting from those files as well?

Get the files here: https://www.dropbox.com/sh/2k6fn2dcvtejvbp/AAC-Fn14gYdJAQtMVSISrpfta?dl=0

**Comment by glampert** [comment]
Hi @masterjg,
First of all apologies for the long hiatus on this.

I've now fixed the issues with invalid Priority flag and failure to decompress zero-sized/invalid file entries. It also only required a couple of minor tweaks to be able to extract Dungeon Siege 2 Tank files, so those should also now be support as well. I've tested with both samples provided by @jsmars (Expansion.dsres and Objects.ds2res) and they extracted without issues.

New prebuild Window x64 binaries can be found in the following zip folder:
https://github.com/glampert/reverse-engineering-dungeon-siege/blob/master/build/Release_Win10_x64.zip
